{{- if .Values.nats.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rayolly.fullname" . }}-nats
  labels:
    {{- include "rayolly.labels" . | nindent 4 }}
    app.kubernetes.io/component: nats
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4222
      targetPort: client
      protocol: TCP
      name: client
    - port: 6222
      targetPort: cluster
      protocol: TCP
      name: cluster
    - port: 8222
      targetPort: monitor
      protocol: TCP
      name: monitor
  selector:
    {{- include "rayolly.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nats
{{- end }}
